name: Test Release
on:
  push:
    branches:
      - test-releases

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install git if missing # Containers used by nektos/act don't have git preinstalled
        run: if ! which git &> /dev/null; then apt-get update && apt-get install -y git; fi;
      - uses: ./
        id: release
      - name: Print output
        if: ${{ steps.release.outputs.released == 'true' }}
        run: echo Release HTML url ${{ steps.release.outputs.html_url }} ID ${{ steps.release.outputs.release_id }} Tag ${{ steps.release.outputs.release_tag }} Name ${{ steps.release.outputs.release_name }}
